theme: jekyll-theme-time-machine
title: Welcome to my first HomePage!!! 
description: Feel free to follow my progress as I learn new skills! I wonder if I just keep typing how it will wrap around the page. WIll it have emough rooom to showw all of my changes, or will it cut off some?
